# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6579e27cb83ec4cc9a61521880fcfac633c3a480313a5aa957aeced63afddf9975715057b9cec5f761c8c18f93c7f6a5e743edc5b197e2041841347dced37cb6

test:
  secret_key_base: f61ff197baa1198106c8c327a33a39d319d474bbd1d1b4e19313136a363a9f979bccdb68c1e57aa5ae9a18f5e167aa41f22a3af30646e4fd3a8ee00175608a2e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
